springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/testing"
    username: "postgres"
    password: "root"
    tomcat:
      max-active: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
        show-sql: false
  data:
    web:
      pageable:
        default-page-size: 10
server:
  port: 5021
